conventional-changelog/conventional-changelog

packages/git-semver-tags/cli.js, packages/git-semver-tags/index.js, packages/git-semver-tags/test.js
@Tapppi reopening this discussion here.
I believe I addressed your two comments 👍
=> fix: address @Tapppi's code-review of lerna semver-tags setting

packages/conventional-changelog/README.md
Shows how a custom, non-standard preset can be used.
=> docs: update usage example

packages/conventional-changelog-core/lib/merge-config.js, packages/conventional-changelog-core/test/test.js
Before this PR, it always add a leading "v" to version number.
After this PR, based on the previous commit tag, it may add or remove the leading "v".
Closes https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/pull/15
Fixes https://github.com/conventional-changelog-archived-repos/conventional-changelog-core/issues/10
=> feat(context): default currentTag may not prefix with v

README.md, packages/conventional-changelog-cli/README.md, packages/conventional-changelog/README.md
Allow users to reach project maintainers by providing the gitter badge up front
=> docs(readme): pull up gitter badge to root

packages/conventional-commits-parser/README.md, packages/conventional-commits-parser/lib/parser.js, packages/conventional-commits-parser/test/parser.spec.js
* introduces options.commentChar
* do not strip comment lines by default
* document new option
* closes #251
=> feat: make comment stripping optional

packages/conventional-recommended-bump/presets/eslint.js, packages/conventional-recommended-bump/test/eslint.js
As title, add eslint preset supports
=> feat(recommended-bump): add `eslint` preset

README.md
=> docs(readme): remove validate-commit-msg from readme.md

.gitignore, .travis.yml, appveyor.yml, package-lock.json, package.json, packages/conventional-changelog-angular/package-lock.json, packages/conventional-changelog-atom/package-lock.json, packages/conventional-changelog-cli/package-lock.json, packages/conventional-changelog-codemirror/package-lock.json, packages/conventional-changelog-core/package-lock.json, packages/conventional-changelog-ember/package-lock.json, packages/conventional-changelog-eslint/package-lock.json, packages/conventional-changelog-express/package-lock.json, packages/conventional-changelog-jquery/package-lock.json, packages/conventional-changelog-jshint/package-lock.json, packages/conventional-changelog-preset-loader/package-lock.json, packages/conventional-changelog-writer/package-lock.json, packages/conventional-changelog/package-lock.json, packages/conventional-commits-filter/package-lock.json, packages/conventional-commits-parser/package-lock.json, packages/conventional-recommended-bump/package-lock.json, packages/git-raw-commits/package-lock.json, packages/git-semver-tags/package-lock.json, packages/gulp-conventional-changelog/package-lock.json, packages/standard-changelog/package-lock.json
Enable Lerna hoisting to reduce package dependency installation time,
and add `npm@5` lockfiles, `package-lock.json`, to improve build
reproducibility.
Closes #269
=> chore(package): enable Lerna hoisting and lockfiles

packages/conventional-changelog-angular/README.md, packages/conventional-changelog-angular/conventional-recommended-bump.js, packages/conventional-changelog-angular/parser-opts.js, packages/conventional-changelog-angular/test/test.js, packages/conventional-changelog-angular/writer-opts.js
Adapted to the new Angular Commit Conventions according to https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type
=> [Angular Package] Adapt to new Angular Commit Conventions

packages/conventional-changelog-angular/templates/header.hbs, packages/conventional-changelog-atom/templates/header.hbs, packages/conventional-changelog-codemirror/templates/header.hbs, packages/conventional-changelog-ember/templates/header.hbs, packages/conventional-changelog-eslint/templates/header.hbs, packages/conventional-changelog-jquery/templates/header.hbs, packages/conventional-changelog-jshint/templates/header.hbs, packages/conventional-changelog-writer/README.md, packages/conventional-changelog-writer/templates/header.hbs, packages/conventional-changelog-writer/test/index.spec.js, packages/conventional-changelog-writer/test/partial.header.spec.js
=> Remove anchor from header templates

packages/conventional-changelog-cli/README.md
=> docs(conventional-changelog-cli): fix link to presets

packages/conventional-changelog-cli/cli.js
=> fix: add missing context flag

packages/conventional-changelog-cli/README.md
Correct npm version path -> patch typo.
=> Fix typo - README.md

package-lock.json, packages/conventional-changelog-eslint/README.md
I added the missing tag for the ESLint commit convention.
fix #403
=> docs(eslint): added "Chore" tag

packages/conventional-changelog-conventionalcommits/README.md, packages/conventional-changelog-conventionalcommits/writer-opts.js
switching to adhere to the configuration specification being fleshed out [here](https://github.com/conventional-changelog/conventional-changelog-config-spec).
=> fix: adhere to config spec

packages/conventional-changelog-conventionalcommits/add-bang-notes.js, packages/conventional-changelog-conventionalcommits/conventional-recommended-bump.js, packages/conventional-changelog-conventionalcommits/parser-opts.js, packages/conventional-changelog-conventionalcommits/test/test.js, packages/conventional-changelog-conventionalcommits/writer-opts.js, packages/conventional-recommended-bump/test/index.spec.js
BREAKING CHANGE: if `!` is in the commit header, it now indicates a BREAKING CHANGE, and the description is used as the body.
=> feat: ! without BREAKING CHANGE should be treated as major

packages/conventional-changelog-writer/package.json
Fix for a security vulnerability
=> Updates handlebars dependency

packages/conventional-changelog-conventionalcommits/templates/commit.hbs, packages/conventional-changelog-conventionalcommits/test/test.js, packages/conventional-changelog-conventionalcommits/writer-opts.js
fixes conventional-changelog/conventional-changelog-config-spec#19
=> feat(preset, conventionalcommits): Add handling of issue prefixes

packages/conventional-changelog-cli/test/test.js, packages/conventional-changelog-conventionalcommits/index.js, packages/conventional-changelog-conventionalcommits/package.json
=> fix(preset, conventionalcommits): fix handling conventionalcommits preset without config object

.gitignore, package-lock.json, package.json, packages/conventional-changelog-preset-loader/package.json, packages/conventional-changelog-writer/package.json, packages/conventional-commits-parser/package.json, packages/conventional-recommended-bump/package.json, packages/git-raw-commits/package.json, packages/git-semver-tags/package.json, packages/standard-changelog/package.json
a bit more sweeping of an update of deps.
=> chore: update deps

package-lock.json, packages/conventional-changelog-cli/package.json, packages/conventional-changelog-writer/package.json, packages/conventional-commits-parser/package.json, packages/conventional-recommended-bump/package.json, packages/git-raw-commits/package.json, packages/git-semver-tags/package.json, packages/standard-changelog/package.json
Not quite sure why the updates from renovate haven't been passing tests, but let's give this a shot.
=> deps: update meow

packages/conventional-commits-filter/index.js, packages/conventional-commits-filter/package.json, packages/git-raw-commits/index.js, packages/git-raw-commits/package.json
https://lodash.com/per-method-packages
=> fix: align lodash dependency across packages

README.md
Tom from Codecov here. Just updating the badge as it looks like you are using Codecov for coverage metrics now.
=> Update to Codecov badge

packages/conventional-commits-parser/lib/parser.js, packages/conventional-commits-parser/test/parser.spec.js
=> fix: Handle missing header in merge commit

packages/conventional-changelog-cli/cli.mjs, packages/conventional-changelog-cli/package.json, packages/conventional-changelog-cli/test/index.spec.js, packages/conventional-changelog-core/lib/merge-config.js, packages/conventional-changelog-core/package.json, packages/conventional-changelog-writer/cli.mjs, packages/conventional-changelog-writer/package.json, packages/conventional-changelog-writer/test/test-cli.js, packages/conventional-commits-parser/cli.mjs, packages/conventional-commits-parser/package.json, packages/conventional-commits-parser/test/test-cli.js, packages/conventional-recommended-bump/cli.mjs, packages/conventional-recommended-bump/package.json, packages/git-raw-commits/cli.mjs, packages/git-raw-commits/package.json, packages/git-semver-tags/cli.mjs, packages/git-semver-tags/package.json, packages/standard-changelog/cli.mjs, packages/standard-changelog/package.json, packages/standard-changelog/test/cli.spec.js, pnpm-lock.yaml
=> fix: fix semver vulnerability

package.json, packages/conventional-changelog-angular/package.json, packages/conventional-changelog-atom/package.json, packages/conventional-changelog-cli/package.json, packages/conventional-changelog-codemirror/package.json, packages/conventional-changelog-conventionalcommits/package.json, packages/conventional-changelog-core/package.json, packages/conventional-changelog-ember/package.json, packages/conventional-changelog-eslint/package.json, packages/conventional-changelog-express/package.json, packages/conventional-changelog-jquery/package.json, packages/conventional-changelog-jshint/package.json, packages/conventional-changelog-preset-loader/package.json, packages/conventional-changelog-writer/package.json, packages/conventional-changelog/package.json, packages/conventional-commits-filter/package.json, packages/conventional-commits-parser/package.json, packages/conventional-recommended-bump/package.json, packages/git-raw-commits/package.json, packages/git-semver-tags/package.json, packages/gulp-conventional-changelog/package.json, packages/standard-changelog/package.json
BREAKING CHANGE: Node >= 16 is required
=> feat!: drop node 14 support

packages/conventional-changelog-conventionalcommits/package.json
=> fix(conventional-changelog-conventionalcommits): include constants.js in package

packages/conventional-changelog-cli/README.md
I simply just changed from "you" to "your"
=> Made a simple grammatical contribution

packages/git-semver-tags/index.js
=> fix(git-semver-tags): make sure that tags are sorted by date

packages/conventional-changelog-conventionalcommits/conventionalRecommendedBump.js, packages/conventional-changelog-conventionalcommits/utils.js
=> chore(conventional-changelog-conventionalcommits): fix addBangNotes usage

.github/workflows/ci.yaml, .github/workflows/release-submodules-manual.yaml, .github/workflows/release-submodules.yaml, package.json, packages/conventional-changelog-angular/package.json, packages/conventional-changelog-atom/package.json, packages/conventional-changelog-cli/package.json, packages/conventional-changelog-codemirror/package.json, packages/conventional-changelog-conventionalcommits/package.json, packages/conventional-changelog-core/package.json, packages/conventional-changelog-ember/package.json, packages/conventional-changelog-eslint/package.json, packages/conventional-changelog-express/package.json, packages/conventional-changelog-jquery/package.json, packages/conventional-changelog-jshint/package.json, packages/conventional-changelog-preset-loader/package.json, packages/conventional-changelog-writer/package.json, packages/conventional-changelog/package.json, packages/conventional-commits-filter/package.json, packages/conventional-commits-parser/package.json, packages/conventional-recommended-bump/package.json, packages/git-client/package.json, packages/git-raw-commits/package.json, packages/git-semver-tags/package.json, packages/gulp-conventional-changelog/package.json, packages/standard-changelog/package.json
BREAKING CHANGE: Node >= 18 is required
=> feat!: drop node 16 support

.commitlintrc.js, packages/conventional-changelog-cli/cli.js, packages/conventional-recommended-bump/src/cli/index.ts, packages/conventional-recommended-bump/src/cli/utils.ts, packages/standard-changelog/cli.js, packages/standard-changelog/test/cli.spec.js
now config can be .js or .json file
closes #1153 #1156 #1221
=> fix(conventional-changelog-cli,conventional-recommended-bump,standard-changelog): fix config loading

packages/conventional-changelog-core/test/index.spec.js, packages/conventional-recommended-bump/src/bumper.ts, packages/conventional-recommended-bump/src/cli/options.ts, packages/conventional-recommended-bump/src/types.ts, packages/git-client/src/ConventionalGitClient.ts, packages/git-client/src/GitClient.spec.ts, packages/git-client/src/GitClient.ts, packages/git-client/src/types.ts, packages/git-client/src/utils.spec.ts, packages/git-client/src/utils.ts, vite.config.js
If you need more git options, please open PR with it.
BREAKING CHANGE: ability to pass additional git params is removed
=> fix(git-client)!: ability to pass additional git params is removed by security reasons

packages/conventional-commits-parser/src/CommitParser.spec.ts, packages/conventional-commits-parser/src/CommitParser.ts, packages/conventional-commits-parser/src/utils.ts
=> feat(conventional-commits-parser): named capturing groups support for regex patterns
