CONVENTIONS.md

The CONVENTIONS.md doc does mention 'breaking changes', but does
not explain the actual format used.
This patch adds some sentences explaining how to markup your commits
to generate beaking changes sections.

docs(CONVENTIONS): explain how to format breaking changes

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-changelog-core/package.json
packages/conventional-changelog-core/readme.md
packages/conventional-changelog-core/test/test.js

makes it possible to pass lerna configuration settings to `gitSemverTags`, and adds tests experimenting with the lerna repository support I've been working on.
see: #168 
```js
var conventionalChangelogCore = require('../conventional-changelog-core');
conventionalChangelogCore({
lernaPackage: 'git-raw-commits',
config: require('../conventional-changelog-angular')
}, {}, {
path: './'
})
.pipe(process.stdout); // or any writable stream
```
The above code seems to work like a charm.
```md
<a name="1.1.2"></a>
* add support for listing lerna style tags (project[@version](https://github.com/version)) (#161) ([b245f9d](https://github.com/stevemao/git-semver-tags/commit/b245f9d))
* migrate repo to lerna mono-repo ([793e823](https://github.com/stevemao/git-semver-tags/commit/793e823))
```

feat: wire up lerna repository support

---

packages/conventional-changelog-cli/cli.js
packages/standard-changelog/cli.js

for easier testing, add support for lerna-style CHANGELOG generation to `conventional-changelog-cli` and `standard-changelog`.

feat: update CLI tools to support lerna tags

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-changelog-core/package.json
packages/conventional-changelog-core/test/test.js

`context.currentTag`, which is used by `conventional-changelog-angular`, should take into account the lerna style tag format.

feat: context.currentTag should take into account lerna tag format

---

lerna.json
package.json

This switches us to a canary release of conventional-commits that supports conventional commits.

chore: switch to version of lerna that supports conventional-commits

---

packages/conventional-changelog-core/readme.md

There is a typo the `lernaPackage` option docs. It states that the structure should be `./package/foo-package` but according to lerna docs and also the [`conventional-changelog-core` unit tests](https://github.com/conventional-changelog/conventional-changelog/blob/431598a3b12a404aee63f8ab3e51263121cde485/packages/conventional-changelog-core/test/test.js#L1222) it should be `./packages/foo-package`

docs: fix typo in `lernaPackage` option docs

---

README.md

conventional-changelog-lint now is called commitlint.

docs(readme): renamed to commitlint

---

packages/conventional-changelog-angular/index.js
packages/conventional-changelog-angular/package.json

* smarten up logic to find a "root" package json a bit
* use pkg-up to find "root"
* use load-json-file for nice error messages
* move module scope procedure to getPkg
* handle missing package.json without logged warning
* propagate possible json errors

fix: find package.json from cwd upwards

---

packages/conventional-changelog-angular/package.json
packages/conventional-changelog-atom/package.json
packages/conventional-changelog-codemirror/package.json
packages/conventional-changelog-core/package.json
packages/conventional-changelog-ember/package.json
packages/conventional-changelog-eslint/package.json
packages/conventional-changelog-express/package.json
packages/conventional-changelog-jquery/package.json
packages/conventional-changelog-jshint/package.json
packages/conventional-changelog-writer/package.json
packages/conventional-changelog/package.json
packages/conventional-commits-parser/package.json
packages/conventional-recommended-bump/package.json
packages/standard-changelog/package.json

There's some malformed JSON in the changelog-core tests that is breaking some build tooling I'm working on.
Since you're already using `package.json#files` in some places, I figured you'd want to use it everywhere.
I went through each package and checked to make sure all the necessary files were included.

Add package.json#files field to all packages

---

packages/conventional-changelog-angular/index.js
packages/conventional-changelog-angular/package.json
packages/conventional-changelog-angular/test/fixtures/_ghe-host.json
packages/conventional-changelog-angular/test/fixtures/_known-host.json
packages/conventional-changelog-angular/test/test.js

This will result in more flexibility since we now use the logic already existing in `conventional-changelog-core` and at the same time make the code simpler. The logic now matches the one already present in [the templates for inserting a link to the commit](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/templates/commit.hbs#L9-L21).
This PR supersedes and replaces #216

feat(angular): use the context for getting the repository and host urls

---

packages/conventional-changelog-angular/index.js
packages/conventional-changelog-angular/test/test.js

Solves issues where incorrect links would be inserted when describing the version of something, like `npm@5`. Now a space is required before a username to be replaced with a link to the profile. 
Closes #218 
---
_This PR has been based on the changes done in #217 and will be rebased on master after it has been merged._

fix(angular): smarter username detection

---

packages/conventional-changelog-cli/README.md
packages/conventional-changelog-core/readme.md
packages/conventional-changelog/README.md
packages/conventional-recommended-bump/README.md
packages/standard-changelog/README.md

Maybe badges in packages should be also updated? (With main repo's ones.)

docs: replace some old links with links to Lerna packages

---

packages/conventional-recommended-bump/package.json

When using `npm home conventional-recommended-bump` the old repository was opened. Now changed to point to the new location.

Update npm home link

---

packages/git-semver-tags/index.js
packages/git-semver-tags/test.js

We recently released `stryker@0.10.0` using Lerna. Ever since this module thinks that `stryker@0.9.3` is the last tag we have. This is because the minor and patch version are only allowed to be one digit. This PR fixes this issue by allowing multiple digits.

fix(lerna tags): Support multi-digit version tags

---

packages/git-raw-commits/README.md
packages/git-raw-commits/index.js

This adds an optional second `opts` argument to `git-raw-commits` intended for options-passing to `child_process.execFile` - specifically this allows to force a cwd for the `git log` process.
**Edit**:
This allows consumers like [commitlint](https://github.com/marionebl/commitlint/blob/master/%40commitlint/core/src/read.js#L37) to decouple command from execution cwd. 
In the first step this makes testing considerably easier. Before I had to change the `cwd` via `process.chdir()` to pick up commit messages from prepared fixture repositories (which forced serial, slow execution) in my tests, now I can specify it via the new option.
For users, this is exposed up to the command line interface to allow for easier scripting, e.g.:
Before
```
cd git-repository
commitlint --from=HEAD^1
cd ..
``` …

feat: allow forced cwd

---

packages/conventional-commits-filter/index.js
packages/conventional-commits-filter/test.js

The change makes sure we only remove reverted commits if they reverted something in the current scope. 
This is useful when we are working with a subset of all commits and want to know if the commits makes sense to list in our changelog. Without this change we would always remove commits that made a revert from the changelog, even if the commit in question was done in a previous release. Now we will only remove the revert commit from the changelog if it reverted something in the current release.
Example using the Angular convention.
```
HASH-3 revert: fix: added something
This reverts commit HASH-1.
HASH-2 chore: release 1.0.1
HASH-1 fix: added something
```
This would make our changelog empty, since the filter with the default configuration would remove it. We would like it to list …

fix(filter): only remove commits that reverted commits in the scope

---

packages/conventional-commits-parser/lib/parser.js
packages/conventional-commits-parser/test/cli.spec.js
packages/conventional-commits-parser/test/index.spec.js
packages/conventional-commits-parser/test/parser.spec.js

* always parse references, regardless of presence of an action
* move reference parsing to reusable function
* adapt test cases to changed behaviour
* fixes #248
* references were dropped from header, body and footer by `parser.sync`
* this happened for references that had no `action` included in `options.referenceActions`
* due to `parser.sync` defaulting to an hardcoded set of `options.referenceActions`, references without (matching) action were never parsed
```js
const parser = require('conventional-commits-parser').sync;
parse('type: subject #1').references;
/* [ ] */
```
* fall back to catch-all regex if options.referenceActions regex produces no matches
* strip reference strings from all `notes`, was inconsistent before
```js
const parser = …
```

fix: always parse references

---

packages/conventional-changelog-cli/README.md
packages/conventional-changelog/README.md

docs: point former conventional-changelog-lint links to commitlint

---

packages/conventional-changelog-eslint/parser-opts.js
packages/conventional-changelog-eslint/test/test.js

The previous regex got a lot of overhead. The new one is easier to read and faster to parse.
But here I changed the regex a bit. First it also matched whitespaces in the beginning of the message, now it doesnt. If the same behavior is wished, I can change the regex to:
```js
/^(\w*): (.*)$/
```
Which does the same as the original one, but with less overhead

feat: regex headerPattern for eslint

---

packages/conventional-changelog-core/test/test.js
packages/conventional-changelog-writer/templates/header.hbs
packages/conventional-changelog-writer/test/index.spec.js
packages/conventional-changelog-writer/test/partial.header.spec.js

Updated the default header template to generate semantic HTML headings using the method suggested by @marcysutton in #214 ✨ 
**Edit:** updated commit message with the following for context:
> Logic for generating release headings has been changed to make all
> heading levels the same (`##`/`h2`) for better compatibility with
> screen readers and parsers, and to conform to HTML semantics. Patch
> release titles are now wrapped in a `<small>` tag to maintain the
> visual hierarchy of the previous style.
> 
> Resolves #214.
> 
> Related issues:
> - #214 (comment)
> - conventional-changelog/standard-version#208

fix(writer): normalize release headings (#214)

---

packages/conventional-recommended-bump/README.md
packages/conventional-recommended-bump/cli.js
packages/conventional-recommended-bump/index.js
packages/conventional-recommended-bump/test/test.js
packages/git-semver-tags/README.md
packages/git-semver-tags/cli.js
packages/git-semver-tags/index.js
packages/git-semver-tags/test.js

This PR adds the possibility to specify a `tagPrefix` in `conventional-recommended-bump`.
Currently is you use a `tagPrefix` in https://github.com/conventional-changelog/standard-version and that tagPrefix is not semver compatible, standard version will not work as intended as it cannot find the releases.
By specifying the tagPrefix in `conventional-recommended-bump` and in turn in `git-semver-tags` we can get a proper version bump recommendation.
If this is accepted `standard-version` will have to be updated to pass the extra parameter to `conventional-recommended-bump`
Thanks in advance for your review

feat: allow to specify a tagPrefix in conventional-recommended-bump

---

packages/gulp-conventional-changelog/index.js
packages/gulp-conventional-changelog/package.json
packages/gulp-conventional-changelog/readme.md
packages/gulp-conventional-changelog/test.js

[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the recently released version 4 of Gulp, it is important to replace `gulp-util`.
See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

refactor: replace deprecated gulp-util

---

packages/conventional-commits-parser/lib/parser.js
packages/conventional-commits-parser/test/parser.spec.js

This resolves an issue where commit authored via `git commit -v` and fed into `conventional-commits-parser` via `.git/COMMIT_EDITMSG` directly where not truncated as intended from the beginning of the scissors line
https://runkit.com/marionebl/conventional-commits-parser-scissors
```js 
const parser = require('conventional-commits-parser');
const message = `A message
diff --git a/package.json b/package.json
index d88860d05..dd6c7818f 100644
--- a/somehting.json
+++ b/somehting.json`;
parser.sync(message, {commentChar: '#'}) // => {body: 'diff --git a/package.json b/packag…mehting.json\n+++ b/somehting.json'}
```
```
const parser = require('conventional-commits-parser');
const message = `A message
diff --git a/package.json b/package.json
index d88860d05..dd6c7818f 100644
--- …
```

fix: truncate after scissors line

---

packages/conventional-changelog-cli/cli.js
packages/conventional-changelog-cli/package.json
packages/conventional-changelog-cli/test/fixtures/promise-config.js
packages/conventional-changelog-cli/test/test.js

Closes #227 
Setting this up allows the core to properly load the configuration (handling promises or however the config is delivered). Otherwise nothing is loaded and a default config is used instead.

fix(cli): set options.config to loaded custom config for processing

---

packages/conventional-changelog-preset-loader/package.json

I tried installing conventional-changelog-preset-loader today and suddenly I had transitive runtime dependencies on chai, jshint, etc. cc @hbetts

preset-loader dependencies -> devDependencies

---

packages/conventional-changelog-eslint/conventional-recommended-bump.js

In a project, we recently started to use `conventional-recommended-bump` (version 2.0.6) and it was giving us wrong results with `npx conventional-recommended-bump -p eslint`. The latest version that works with `-p eslint` seems to be 1.2.1 (with built-in presets).
It seems that the Angular preset was inadvertently copied into the ESLint package with commit 60815b50bc68b50a8430c21ec0499273a4a1c402.
This corrects the `conventional-recommended-bump` ESLint preset in `conventional-changelog-eslint` to behave the same as the built-in ESLint preset that was removed with #270.
Related to #241

fix(preset): recommended-bump ESLint preset

---

LICENSE.md
packages/conventional-changelog-angular/LICENSE.md
packages/conventional-changelog-atom/LICENSE.md
packages/conventional-changelog-codemirror/LICENSE.md
packages/conventional-changelog-core/LICENSE.md
packages/conventional-changelog-ember/LICENSE.md
packages/conventional-changelog-eslint/LICENSE.md
packages/conventional-changelog-express/LICENSE.md
packages/conventional-changelog-jquery/LICENSE.md
packages/conventional-changelog-jshint/LICENSE.md
packages/conventional-changelog-preset-loader/LICENSE.md
packages/conventional-changelog-writer/LICENSE.md
packages/conventional-changelog/LICENSE.md
packages/conventional-commits-parser/LICENSE.md
packages/conventional-recommended-bump/LICENSE.md
packages/git-raw-commits/LICENSE.md
packages/git-semver-tags/LICENSE.md
packages/gulp-conventional-changelog/LICENSE.md
packages/standard-changelog/LICENSE.md

Add a license file with the license text of the MIT license.
Fixes #286

Add license file

---

packages/conventional-changelog-core/README.md
packages/conventional-changelog-core/lib/merge-config.js

Following my previous PR, I'm now looking at how to consume this properly in `standard-version` and I noticed that I forgot to pass the parameter in one place...
This PR fixes that ! The original PR can be found here https://github.com/conventional-changelog/conventional-changelog/pull/259
During the `merge-config` part of conventional-changelog-core a call is made to `gitSemverTags` to retrieve the list of tags so that the changelog can compare the previous one with the change made so far.
This call was not passing the `tagPrefix` parameter so was failing to retrieve the correct tag list !
@hbetts @bcoe please review

fix: `tagPrefix` was not passed properly in conventional-changelog-core

---

packages/conventional-changelog-angular/templates/header.hbs
packages/conventional-changelog-atom/templates/header.hbs
packages/conventional-changelog-codemirror/templates/header.hbs
packages/conventional-changelog-ember/templates/header.hbs
packages/conventional-changelog-eslint/templates/header.hbs
packages/conventional-changelog-jquery/templates/header.hbs
packages/conventional-changelog-jshint/templates/header.hbs
packages/conventional-changelog-writer/README.md
packages/conventional-changelog-writer/templates/header.hbs
packages/conventional-changelog-writer/test/index.spec.js
packages/conventional-changelog-writer/test/partial.header.spec.js

Closes #186.
BREAKING CHANGE:
Anchor tags are removed from the changelog header templates. The
rendered Markdown will no longer contain anchor tags proceeding the
version number header that constitutes the changelog header. This means
that consumers of rendered markdown will not be able to use a URL that
has been constructed to contain a version number anchor tag reference,
since the anchor tag won't exist in the rendered markdown.
It's stronly recomended consumers use the full URL path to the release
page for a given version, as that URL is a permalink to that verison,
contains all relavent release information, and does not, otherwise, rely
on the anchor tag being excessible from the current page view.
As an example, for version `2.0.0` of a GitHub project, the following
URL should be …

refactor: remove anchor from header templates

---

.travis.yml
README.md
appveyor.yml
package.json
packages/conventional-changelog-angular/package.json
packages/conventional-changelog-atom/package.json
packages/conventional-changelog-cli/package.json
packages/conventional-changelog-codemirror/package.json
packages/conventional-changelog-core/package.json
packages/conventional-changelog-ember/package.json
packages/conventional-changelog-eslint/package.json
packages/conventional-changelog-express/package.json
packages/conventional-changelog-jquery/package.json
packages/conventional-changelog-jshint/package.json
packages/conventional-changelog-preset-loader/package.json
packages/conventional-changelog-writer/package.json
packages/conventional-changelog/package.json
packages/conventional-commits-filter/package.json
packages/conventional-commits-parser/package.json
packages/conventional-recommended-bump/package.json
packages/git-raw-commits/package.json
packages/git-semver-tags/package.json
packages/gulp-conventional-changelog/package.json
packages/standard-changelog/package.json

BREAKING CHANGE:
Set the package's minimum required Node version to be the oldest LTS
currently supported by the Node Release working group. At this time,
that is Node 6 (which is in its Maintenance LTS phase).

chore(package): set Node requirement to oldest supported LTS

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-changelog-core/test/test.js

This helps to recreate a fresh and clean changelog in the event of conventions having changed or in case of random hiccups (such as lines duplication)

feat(core): ability to reset changelog from scratch

---

packages/conventional-changelog-cli/cli.js

closes #337 
I did not found any contribution guide to this repo. Are there any intorduction on how to test this on my local machine? I just copied the parts from `lerna-package` as they should work the same way.

fix(cli): pass `--tag-prefix` option to core

---

packages/conventional-changelog-eslint/conventional-recommended-bump.js

Recommended version bump detection with ESLint preset is broken since
`conventional-changelog-eslint` version 3.0.0:
`npx conventional-recommended-bump -p eslint` always returns "patch".
This is because the preset's `parserOpts` (re-used with v3.0.0)
"headerCorrespondence" is set to `['tag', 'message']` rather than
`['type', 'subject']`, which was used before in the [ESLint preset
"conventional-recommended-bump" specific `parserOpts`][1].
This adapts the ESLint preset's `whatBump` implementation to check "tag"
instead of "type", which fixes the issue.
[1]: https://github.com/conventional-changelog/conventional-changelog/blob/ce1fd981f88ce201e996dfa833e4682de3aafcdd/packages/conventional-changelog-eslint/conventional-recommended-bump.js#L32-L35

fix(preset): ESLint recommended-bump is always "patch"

---

packages/conventional-changelog-angular/test/test.js
packages/conventional-changelog-angular/writer-opts.js

GitHub username detection of Angular preset detects scoped NPM packages as GitHub username, package `@dummy/package` will be replaced by `[@dummy](https://github.com/dummy)/package` in the changelog.
With this patch, scoped NPM packages won't be detected as GitHub username:

fix(preset:angular): Scoped NPM packages are not seen as GitHub username anymore

---

package-lock.json
package.json
packages/conventional-changelog-writer/package.json

addresses https://www.npmjs.com/advisories/755

chore: update handlebars dependency

---

packages/conventional-recommended-bump/index.js
packages/conventional-recommended-bump/test/index.spec.js

In custom scenarios it is useful to get some context of the current options of the `conventionalRecommendedBump` call.
For example, when using a custom changelog preset together with Lerna, and the preset uses a custom `whatBump` method that requires to know the current Lerna package that it is being run for.
See: https://github.com/lerna/lerna/blob/a6733a2b864cf9d082d080bbd3bfedb04e59b0ab/core/conventional-commits/lib/recommend-version.js#L13-L21

feat: send options to whatBump

---

README.md

It's a part of conventional-changelog ecosystem

docs: add vscode extension link to README.md

---

packages/conventional-commits-filter/index.js
packages/conventional-commits-filter/package.json

This replace [is-subset](https://github.com/studio-b12/is-subset) with [lodash.isMatch](https://lodash.com/docs/4.17.10#isMatch).
`is-subset` doesn't seems to be maintained anymore (last commit from October 2015) and it currently has a bug that prevent to use [pkg](https://github.com/zeit/pkg): https://github.com/studio-b12/is-subset/pull/9.
As a result any module that depends on `conventional-commits-filter` cannot be bundled with [pkg](https://github.com/zeit/pkg).

fix(filter): replace `is-subset` with `lodash.ismatch`

---

packages/conventional-changelog-conventionalcommits/README.md
packages/conventional-changelog-conventionalcommits/test/test.js
packages/conventional-changelog-conventionalcommits/writer-opts.js

I've written some more tests ensuring that various aspects of the conventionalcommits.org specification are adhered to; in the process I've fixed a few things.
* types should not need to be case sensitive (I've added a test for this and fixed a bug).
* user URLs were tied to GitHub, I've made this configurable now.
* I've added a test ensuring that footers can be multiple lines (in the process I found a [bug](https://github.com/conventional-changelog/conventional-changelog/issues/428).

fix: address discrepancies between cc preset and spec

---

packages/conventional-changelog-conventionalcommits/conventional-recommended-bump.js
packages/conventional-changelog-preset-loader/index.js
packages/conventional-changelog/index.js
packages/conventional-recommended-bump/index.js
packages/conventional-recommended-bump/test/index.spec.js

This PR introduces the `preMajor` config option for the conventionalcommits preset.
When set to `true`, breaking changes will still be populated in `reasons` but a `minor` version bump will be recommended rather than a `major`.
----
when landing #421 I neglected to pass the new preset object to recommended bump; this PR:
1. Pulls the logic into `conventional-changelog-preset-loader` so that it's shared by both `conventional-changelog` and recommended bump.
2. introduces the `preMajor` config option ([documented here](https://github.com/conventional-changelog/conventional-changelog-config-spec/pull/4)); which is required by `standard-version`, and is used in unit-tests to ensure the preset is getting passed configuration.

feat: conventionalcommits preset, preMajor config option

---

packages/conventional-changelog-conventionalcommits/package.json

Fixes #436.
Tested with 6.9.0, and it works.

fix: Downgrade node 10.x dependency to 6.9.0 dependency

---

packages/conventional-changelog-conventionalcommits/templates/header.hbs

CHANGELOGS should not contain multiple H1 tags.

fix: template should not include multiple H1 tags

---

packages/conventional-changelog-conventionalcommits/parser-opts.js
packages/conventional-changelog-conventionalcommits/test/test.js

Adds support for optional `!` character to indicate breaking changes. [see](https://github.com/conventional-commits/conventionalcommits.org/issues/43)
BREAKING CHANGE: a ! character at the end of type will now be omitted

feat!: add support for !

---

packages/conventional-changelog-cli/README.md

Restarting the changelog and using the `npm version` script doesn't make sense.

docs(README): Changed npm script to append to the changelog

---

packages/conventional-changelog-conventionalcommits/add-bang-notes.js
packages/conventional-changelog-conventionalcommits/test/test.js

if someone had a commit message along these lines:
```
fix(test)!: this is a breaking change
BREAKING CHANGE: this is breaking.
```
It would result in BREAKING CHANGES notes being populated twice.

fix: if ! and BREAKING CHANGE were used, notes would populate twice

---

packages/conventional-changelog-conventionalcommits/writer-opts.js

The conventionalcommits preset allows all URL formats to be configured, such that
host and repository could be populated manually. Removing these fields as a requirment
allows this library to support a wider variety of platforms.

fix: don't require 'host' and 'repository'

---

packages/conventional-changelog-cli/cli.js

fix(cli.js): fix issue where standard conventional-changelog options are not passed into the options object using --config flag

fix(cli): fix issue to pass conventional-changelog standard options cli.js

---

packages/conventional-changelog-conventionalcommits/test/test.js
packages/conventional-changelog-conventionalcommits/writer-opts.js

- adds conditionals around commit context for host, owner and repository.
closes #462

fix(preset, conventionalcommits): Ensure proper substitutions for the conventionalcommit preset by using commit context for values where possible.

---

package-lock.json
packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-recommended-bump/index.js
packages/git-semver-tags/README.md
packages/git-semver-tags/cli.js
packages/git-semver-tags/index.js
packages/git-semver-tags/test.js

e.g. `(opts, callback)`
Also, allow passing `opts.cwd` ... because it currently fails if you want to listen on another directory
Also. I would go with `Object.assign`, but was not sure for the require node version in CI.

[git-semver-tags]: BREAKING: switch params, make it normal node-style signature

---

packages/conventional-changelog-cli/package.json

- Resolves a security warning in lodash (CVE-2019-10744)
closes #486

fix(deps, cli): bumps (minor + patch) lodash in conventional-changelog-cli

---

packages/conventional-changelog-preset-loader/index.js
packages/conventional-changelog-preset-loader/test/test.js

It's rather surprising and confusing esp. with scoped packages that the CLI effectively requires using an option like `--preset=@scope/preset` in order to fetch the preset defined in `@scope/conventional-changelog-preset`.
This change allows for the loader to also handle full package paths, so that with the above example `--preset=@scope/conventional-changelog-preset` would work.

Allow use of full package names when loading presets

---

packages/conventional-changelog-cli/test/test.js
packages/conventional-changelog-preset-loader/index.js

fix(preset-loader): fix handling conventionalcommits preset without config object

fix(preset-loader): fix handling conventionalcommits preset without config object

---

package.json
packages/conventional-changelog-conventionalcommits/test/test.js
packages/conventional-changelog-conventionalcommits/writer-opts.js

@tommywo @jbottigliero small tweak to improve readability of CHANGELOG, features will now be displayed above fixes.

feat: sort sections of CHANGELOG based on priority

---

packages/conventional-changelog-eslint/templates/commit.hbs
packages/conventional-changelog-eslint/writer-opts.js

Fixes current problem where ESLIint generates release notes using the full hash like shown below.

fix(eslint): display short tag in release notes (closes #313)

---

packages/conventional-changelog-angular/templates/commit.hbs
packages/conventional-changelog-angular/writer-opts.js
packages/conventional-changelog-atom/templates/commit.hbs
packages/conventional-changelog-atom/writer-opts.js
packages/conventional-changelog-codemirror/templates/commit.hbs
packages/conventional-changelog-codemirror/writer-opts.js
packages/conventional-changelog-conventionalcommits/templates/commit.hbs
packages/conventional-changelog-conventionalcommits/writer-opts.js
packages/conventional-changelog-ember/writer-opts.js
packages/conventional-changelog-jquery/templates/commit.hbs
packages/conventional-changelog-jquery/writer-opts.js
packages/conventional-changelog-jshint/templates/commit.hbs

fixes  #476
conventional-changelog/standard-version#452

fix: use full commit hash in commit link

---

package-lock.json
packages/conventional-changelog-cli/package.json
packages/conventional-changelog-conventionalcommits/package.json
packages/conventional-changelog-core/package.json
packages/conventional-changelog-writer/package.json
packages/conventional-commits-parser/package.json
packages/standard-changelog/package.json

This includes fixes for CVE-2019-1010266, CVE-2019-10744 and
CVE-2018-16487.

fix(deps): update lodash to fix security issue

---

packages/conventional-changelog-preset-loader/index.js
packages/conventional-changelog-preset-loader/test/test.js

Allow the preset package path to be an absolute file path to support Yarn PnP

feat(preset-loader): allow use of absolute package path

---

package-lock.json
packages/conventional-commits-parser/package.json

fix(conventional-commits-parser): downgrade is-text-path due to node 6 incompatibility

---

packages/conventional-commits-parser/lib/parser.js
packages/conventional-commits-parser/test/parser.spec.js

fix #543
For every presets, a breaking can be determined by testing the length of `commit.notes` however the `conventionalcommits` convention specify that a commit can be a breaking change if it has an `!` after the type/scope even if it doesn't have a `BREAKING CHANGE` note in the footer.
So in such case the `notes` property of the parsed commit will be an empty array and there is no way to determine if the parsed commit is a breaking or not.
This PR add something similar to what `conventional-changelog-conventionalcommits` does for the writer: https://github.com/conventional-changelog/conventional-changelog/blob/63d8cbedd24d957c759865211dd2341fd4a3e1f2/packages/conventional-changelog-conventionalcommits/writer-opts.js#L65
The commit `feat!: breaking change feature` will now be parsed …

parser: add breaking change notes if header match `breakingHeaderPattern`

---

packages/conventional-commits-parser/cli.js
packages/conventional-commits-parser/test/cli.spec.js

fix https://github.com/conventional-changelog/conventional-changelog/issues/539
Adds a separator to the non tty path with unit test

fix(conventional-commits-parser): Added missing separator pipe to non tty parser

---

packages/conventional-changelog-core/index.js
packages/conventional-changelog-core/lib/merge-config.js

Fixes #479 
This allows a new param to be provided to core that are passed to git-raw-commit as exec option, notable, now being able to change the cwd from a calling function.
If no value provided, it'll work normally as `cwd` is defaulted to the `process.cwd()` value when falsy.

feat(gitExecOpts): Provide facility to define options.

---

package-lock.json
packages/conventional-changelog-core/index.js
packages/conventional-changelog-core/package.json
packages/conventional-changelog-core/test/test.js

Call `gitRawCommits` with ranges `[tag1..tag2, tag2..tag3, ..., tagX..HEAD]` to make sure commits are returned in right order.
fixes #408

Respect commits merge order

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-changelog-core/test/test.js

fix(conventional-changelog-core): read current version properly when tagPrefix is provided

---

packages/git-semver-tags/cli.js

BREAKING CHANGE: --tagPrefix flag was changed to --tag-prefix
closes #553

fix(git-semver-tags): change --tagPrefix flag to --tag-prefix

---

packages/conventional-changelog-core/index.js
packages/conventional-changelog-core/test/test.js

fix(conventional-changelog-core): fix duplicated commits when `from` is specified

---

packages/conventional-commits-parser/index.js
packages/conventional-commits-parser/test/index.spec.js

Currently, if you're using a "/" character in the scope of your commit and using the default option for "headerPattern", the Regex doesn't match the scope and the commit is considered as invalid.
This pull request adds the "/" character to the default "headerPattern" option.

feat: support slash in headerPattern default options

---

packages/conventional-commits-parser/README.md
packages/conventional-commits-parser/cli.js
packages/conventional-commits-parser/lib/regex.js
packages/conventional-commits-parser/test/regex.spec.js

Currently issuePrefixes are always treated as case insensitive. 
This is problematic for JIRA-type prefixes (i.e. {some-letters}-) as it creates a lot of false positives. Example: `upgrade dependency to foobar-12` causes foobar-12 to be treated as a reference.
This MR adds an option to control that behaviour. The default is `false` so it is backwards compatible.

feat: add issuePrefixesCaseSensitive parser option

---

packages/conventional-recommended-bump/README.md

As you can see #596, I think `options.path` is good to be documented.
Thanks!

docs(conventional-recommended-bump/README): add options.path

---

packages/conventional-changelog-conventionalcommits/conventional-recommended-bump.js
packages/conventional-changelog-conventionalcommits/test/test.js
packages/conventional-changelog-conventionalcommits/writer-opts.js

Implements @jskeet's suggestion [here](https://github.com/conventional-commits/conventionalcommits.org/issues/200), we still need to update the specification accordingly.
@mleguen, I saw your [pr here](https://github.com/yargs/yargs/pull/1509) and it motivated me to update the parser, since it's an easy mistake to make (we don't yet support `feature` in the parser, and landing your PR as is would have broken automation).

feat: add support for 'feature' as alias for 'feat'

---

README.md

It was pointing to a deprecated repo

docs: update readme for gulp plugin

---

packages/conventional-changelog-angular/README.md

The markdown formatting for linking to a section in the same document wasn't working.

Fix conventional-changelog-angular README link

---

packages/conventional-changelog-cli/cli.js
packages/conventional-changelog-core/README.md
packages/conventional-changelog-core/lib/merge-config.js
packages/git-semver-tags/index.js
packages/git-semver-tags/test.js

Hi
during usage of your great tool in our team, we came with this little improvement that makes our lives easier.
During our development workflow we often create a few :smile: release candidates in process, which then makes changelog generation little tricky as their number vary.
This new _--skip-unstable_ simply skips all those (_alpha_, _beta_, _whatever_ too), so the default _--release-count=1_ works as expected.
Maybe this will be useful for some other too.
BR
Arnost

feat: add support for '--skip-unstable' option

---

packages/conventional-changelog-conventionalcommits/templates/commit.hbs

this makes it possible for upstream tooling to provide a `null` has to omit a SHA.

feat(templates): if hash is nullish, do not display in CHANGELOG

---

packages/conventional-commits-parser/lib/parser.js
packages/conventional-commits-parser/test/parser.spec.js

When a commit is signed with GPG and `git config log.showSignature true` has been set, it creates additional lines in the raw commit, in this format:
```
gpg: Signature made Thu Oct 22 12:19:30 2020 EDT
gpg:                using RSA key ABCDEF1234567890
gpg: Good signature from "Author <author@example.com>" [ultimate]
```
Because these lines occur before the "real" commit begins, the commit is not parsed properly.
This PR ignores these additional lines in the commit message, as they are irrelevant to versioning.

fix: ignore gpg lines

---

packages/git-semver-tags/index.js

fix: bug in unstableTagTest causing a mismatch on beta release higher then beta-9

---

packages/conventional-commits-parser/README.md
packages/conventional-commits-parser/lib/regex.js
packages/conventional-commits-parser/test/regex.spec.js

Inspired by #13, I would like to customize the [`RegEx` pattern](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/lib/regex.js#L21) used for notes similar to the option that is [already available for the header pattern](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/lib/parser.js#L169). Using the note keywords does not suffice.
Add an option `notesPattern` that takes a function `(noteKeywords: string) => RegExp`. With this, a user can specify a custom regular expression that incorporates the (already concatenated) note keywords.

feat: allows notes pattern to be customized

---

packages/conventional-changelog-conventionalcommits/test/test.js
packages/conventional-changelog-conventionalcommits/writer-opts.js

Allow matching scope when generating changelog. For instance `chore(deps)` could be included in changelog under its own section while other `chore` is hidden.

feat(conventionalcommits): allow matching scope

---

packages/conventional-changelog-writer/README.md
packages/conventional-changelog-writer/index.js
packages/conventional-changelog-writer/package.json
packages/conventional-changelog-writer/test/index.spec.js

This PR adds a method that allows an array of commit objects to be passed to the writer, rather than piping a stream.
* The streaming API can be burdensome to use when a user of the API has access to an already parsed array of commits.
* We've [noticed bugs related to stream order](https://github.com/googleapis/release-please/pull/581) in some Node.js versions.
* We're currently working on a [formal parser for "Conventional Commits"](https://github.com/conventional-commits/parser), which does not expose a streaming API.

feat: add helper for parsing array of commits

---

packages/conventional-recommended-bump/README.md
packages/conventional-recommended-bump/cli.js
packages/conventional-recommended-bump/index.js

This [feature](https://github.com/conventional-changelog/conventional-changelog/pull/656) is exactly what I need. But I need it also in the conventional-recommended-bump module.
It should be possible to use the --skip-unstable option, of the git-semver-tags module.
_This is the same [PR](https://github.com/conventional-changelog/conventional-changelog/pull/674) but I had some struggle with updating my fork_

feat(conventional-recommended-bump): support for '--skip-unstable'

---

packages/conventional-changelog-writer/README.md
packages/conventional-changelog-writer/lib/util.js
packages/conventional-changelog-writer/package.json

BREAKING CHANGE: nested object properties no longer supported
Refs: https://github.com/googleapis/release-please/issues/601
Refs: https://github.com/googleapis/release-please/pull/581

fix: drop compare-func making sort consistent across node versions

---

packages/git-raw-commits/index.js

@thesmiley1 rolling back for now, until we figure out what we want to do.
one thought, why don't we only add the flag if it's been provided by the user, vs., defaulting the flag to false?
Reverts conventional-changelog/conventional-changelog#671

fix(git-raw-commits): revert "normalize git show signature option to false"

---

packages/conventional-changelog-core/index.js
packages/conventional-changelog-core/package.json

This is only place where `shelljs` is used within code base, this library is also used within tests but its inherited from root package.json #753
https://github.com/conventional-changelog/conventional-changelog/blob/d9feeb605de28c00ef55b5c8e229efd1289dd6e8/package.json#L68
this is simmilar use case as in
https://github.com/conventional-changelog/conventional-changelog/blob/d9feeb605de28c00ef55b5c8e229efd1289dd6e8/packages/git-raw-commits/index.js#L4
https://github.com/conventional-changelog/conventional-changelog/blob/d9feeb605de28c00ef55b5c8e229efd1289dd6e8/packages/git-raw-commits/index.js#L58-L61

dep(conventional-changelog-core): remove unnecessary shelljs

---

.gitignore

.DS_Store - used in macOS - https://en.wikipedia.org/wiki/.DS_Store
.vscode - used by vscode - https://code.visualstudio.com/
.idea - used by webstorm/intelij idea etc. - https://www.jetbrains.com/webstorm/

chore: add editor folders to gitignore

---

packages/conventional-changelog-conventionalcommits/test/test.js
packages/conventional-changelog-conventionalcommits/writer-opts.js

If the special `Release-As` footer is used to correct a bad commit, e.g., merging an unintended breaking change, it should be included in CHANGELOG.

feat(conventionalcommits): include Release-As commits in CHANGELOG

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-changelog-core/package.json

Update `get-pkg-repo` to fix [this](https://github.com/advisories/GHSA-7p7h-4mm5-852v).
Also updated a the return of the `repoUrl` to fix tests.
related: https://github.com/conventional-changelog/conventional-changelog/pull/809

Update get-pkg-repo to ^4.0.0

---

package.json
packages/conventional-changelog-angular/test/fixtures/_unknown-host.json
packages/conventional-changelog-conventionalcommits/test/fixtures/_unknown-host.json
packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-commits-parser/lib/parser.js
packages/conventional-commits-parser/package.json

Fixes: https://github.com/conventional-changelog/conventional-changelog/issues/840
Refs: https://nvd.nist.gov/vuln/detail/CVE-2021-23425
Refs: https://github.com/stevemao/trim-off-newlines/pull/3/files

fix(conventional-commits-parser): address CVE-2021-23425

---

packages/conventional-changelog-cli/cli.js
packages/conventional-changelog/README.md

As I understand it, there should be "conventionalcommits" and should not be "jscs".
Related:
- https://github.com/conventional-changelog/conventional-changelog/pull/421
- https://github.com/conventional-changelog/conventional-changelog/pull/293

fix(docs): update list of available presets

---

packages/conventional-changelog-conventionalcommits/README.md

Placeholders are denoted with two curly braces.
The examples were helpful for a quick start, but I was wondering why the template was not expanded. Needed to look in the source code to find out why and then it was obvious.

docs(conventionalcommits): fix template examples

---

packages/git-raw-commits/index.js
packages/git-raw-commits/test.js

when i use the following code
```js
gitRawCommits({
path: './packages/foo',
since
}).pipe(...)
```
the output is not what I expect. In my opinion [since](https://www.git-scm.com/docs/git-log#Documentation/git-log.txt---sinceltdategt) option does not work
the git-log command:
````bash
git log --format=%B%n------------------------ >8 ------------------------ HEAD -- ./packages/foo --since=2021-12-29T08:48:18.749Z
````
[looks like `-- <path>` should be in the last position](https://www.git-scm.com/docs/git-log#_synopsis)
> `git log [<options>] [<revision range>] [[--] <path>…​]`
So I tried to  put the `-- path` at the end, and it works:
```diff
const gitArgs = ['log', gitFormat, gitFromTo]
+    .concat(dargs(gitOpts, {
+     excludes: ['debug', 'from', 'to', 'format', 'path']
+    }))
// …
```

fix: allow raw commits to be filtered by path and date range

---

packages/conventional-changelog-writer/package.json

CVE-2021-23369 is affected by use the handlebars package
Ref: https://github.com/advisories/GHSA-f2jv-r9rf-7988

fix(deps): patch the handlebars package

---

packages/conventional-recommended-bump/index.js

Providing a way to bypass this issue
closes #924

fix: add possibility to provide custom flags to commit fetcher

---

packages/conventional-changelog-writer/lib/util.js
packages/conventional-changelog-writer/test/index.spec.js

Includes a test that failed prior to this fix.
fixes #1043

fix: properly deep clones the commit before modifying it

---

packages/conventional-recommended-bump/cli.mjs
packages/git-semver-tags/cli.mjs

Option definition for `skip-unstable` are missing in `cli.js` both for `git-semver-tags` and `conventional-recommended-bump`. So when running from command line the `--skip-unstable` opt is not passed to the actual `gitSemverTags` method.
I could not manage to validate the issue with `conventional-recommended-bump` but since it is defined in the `options` object, I've added it to the `meow` definition there too for consistency.
Likely addresses #754 and #675.
Example when running in this very repo:
<details><summary>Before</summary>
```
$ node packages/git-semver-tags/cli.js
v1.1.0
v1.0.2
v1.0.1
v1.0.0
v0.5.3
v0.5.2
v0.5.1
v0.5.0
v0.4.3
v0.4.2
v0.4.1
v0.4.0
v0.3.2
v0.3.1
v0.3.0
v0.2.1
v0.2.0
v0.1.3
v0.1.2
v0.1.1
v0.1.0
v0.1.0-beta.3
v0.1.0-beta.2
v0.1.0-beta.1
v0.1.0-alpha.3
v0.1.0-alpha.2 …
```

fix: define `skip-unstable` in opts so they are passed down to `gitSemverTags`

---

packages/git-raw-commits/README.md
packages/git-raw-commits/index.js
packages/git-raw-commits/test/index.spec.js

We have a use case for creating changelogs for a bundled application where the source code is spread across multiple directories and libs inside a monorepo e.g. `apps/my-app` and `libs/my-app-external-api`, and we'd like to include changes from `libs/my-app-external-api` inside of the changelog for `apps/my-app`. Currently we have patched `git-raw-commits` to allow this, but I think that others may find this useful.

feat(git-raw-commits): add support for multiple paths

---

packages/conventional-changelog-conventionalcommits/test/index.spec.js
packages/conventional-changelog-conventionalcommits/writerOpts.js

This PR allows those of us who use tools other than GitHub to use alphanumeric issues.
Fix: https://github.com/conventional-changelog/conventional-changelog/issues/650

Add support for alphanumeric issues

---

packages/conventional-changelog-writer/cli.mjs
packages/conventional-changelog-writer/package.json
pnpm-lock.yaml

split package is no longer maintained and has been marked as archived,
split2 package is used across repo for same purpose and API of those packages is "same"
https://github.com/conventional-changelog/conventional-changelog/commit/1941c374381688aff57ad2f4c20e6bd8e971bf01#diff-1e6d561d19491fb83fea724e4ac3e5d9ab82e58872a2ff9adbdbc8f08372a0c0R10
https://github.com/conventional-changelog/conventional-changelog/commit/8feb26c5230ed6ddfaebdb8a0d043fc66f6df0b4#diff-45ad27325f1ec4b7be159dc4117df057a9581ae50622def12aed26c0799cdc85R26
https://github.com/dominictarr/split
https://github.com/mcollina/split2
https://github.com/conventional-changelog/conventional-changelog/blob/208494eaff3bb7ab25a89e1151e7538d0806ddd6/packages/conventional-commits-parser/package.json#L39

fix: align split/2 package between packages

---

packages/conventional-changelog-angular/conventionalRecommendedBump.js
packages/conventional-changelog-atom/conventionalRecommendedBump.js
packages/conventional-changelog-codemirror/conventionalRecommendedBump.js
packages/conventional-changelog-ember/conventionalRecommendedBump.js
packages/conventional-changelog-eslint/conventionalRecommendedBump.js
packages/conventional-changelog-express/conventionalRecommendedBump.js
packages/conventional-changelog-jquery/conventionalRecommendedBump.js
packages/conventional-changelog-jshint/conventionalRecommendedBump.js
packages/conventional-changelog-writer/index.js
packages/conventional-changelog-writer/lib/util.js
packages/conventional-changelog-writer/test/index.spec.js
packages/conventional-changelog-writer/test/util.spec.js
packages/conventional-commits-parser/lib/parser.js
pnpm-lock.yaml

Now you can return promises in `transform` and `finalizeContenxt`:
```js
export default {
async transform: (commit, context) => {
return await ...
},
async finalizeContext: (context, options, commits) => {
return await ...
}
}
```
I didn't do complicated refactoring; I just changed most synchronous functions to support asynchronous and passed all tests.
Hope to see this feature in `v6.1.0`.
I'm suffering from adding contributors to [Master CSS releases](https://github.com/master-co/css/releases).

feat(conventional-changelog-writer): support async `options.transform` and `options.finalizeContext` #471

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-changelog-core/package.json
pnpm-lock.yaml

remove no longer maintained wrapper package `get-pkg-repo` and replace it with direct dependencies to `hosted-git-info` and `@hutson/parse-repository-url`,
note:
> this code is not ideal as we are parsing and converting repository URL multiple times, eg. hosted-git-info is already during normalization of package `normalize-package-data` and simmilar logic is applied when package is read in `read-pkg`
this PR simply removes one wrapper and updates dependencies, but i think we should investigate if all of this code is really neccessary or if can be simplified

refactor(conventional-changelog-core): update repository-url parsing

---

packages/conventional-changelog-preset-loader/package.json
pnpm-lock.yaml

This dependency has been missed during migration to vitest in #1067

deps(conventional-changelog-preset-loader): remove unused sinon

---

packages/conventional-commits-parser/cli.mjs
packages/conventional-commits-parser/package.json
pnpm-lock.yaml

follow up for #971
Use simple stream transform instead of JSONStream library,
- [JSONStream](https://github.com/dominictarr/JSONStream) is archived and no longer maintained.
- [through](https://github.com/dominictarr/through) is no longer included in dependency tree

refactor(conventional-commits-parser): use Transform instead of JSONStream

---

packages/conventional-changelog-core/lib/merge-config.js
packages/conventional-recommended-bump/README.md
packages/conventional-recommended-bump/cli.mjs
packages/conventional-recommended-bump/index.js
packages/conventional-recommended-bump/package.json
packages/conventional-recommended-bump/test/index.spec.js
packages/git-semver-tags/README.md
packages/git-semver-tags/cli.mjs
packages/git-semver-tags/index.js
packages/git-semver-tags/test/index.spec.js
pnpm-lock.yaml

BREAKING CHANGE: gitSemverTags and conventionalRecommendedBump now return promises

feat!(git-semver-tags,conventional-recommended-bump): refactoring to use promises instead of callbacks

---

packages/conventional-changelog-conventionalcommits/conventionalRecommendedBump.js
packages/conventional-recommended-bump/test/index.spec.js

It throws error, when the preset option is set to the string `conventionalcommits`.

fix(conventional-changelog-conventionalcommits): optional config

---

packages/conventional-changelog-cli/cli.js

This is clearly breaked due to https://github.com/conventional-changelog/conventional-changelog/pull/1144 which missed this link's update

fix(conventional-changelog-cli): wrong link for option prompt

---

packages/conventional-changelog-writer/README.md
packages/conventional-changelog-writer/index.js
packages/conventional-changelog-writer/test/index.spec.js

Hi there. I'm a user of this project.
Sorry... I use deepl because I am not good at English. 
I've faced a problem that same as #594. 
I created the PR because I thought it would be better to be able to set timeZone in writerOpts.
add timezone option to writerOpts(https://github.com/conventional-changelog/conventional-changelog/issues/594#issuecomment-587168242)
The default value is 'UTC' to avoid breaking changes in the conventional-changelog-writer.
```js
// option.js
export default {
writerOpts: {
timeZone: "Ameraica/Los_Angeles"
}
}
```
```
$ conventional-changelog -p angular -i CHANGELOG.md -s  -n option.js
```
When a non-existent timezone is specified, I get an error like the following.
Or should I catch the error?
```js
// option.js
export default {
writerOpts: {
timeZone: …
```

feat(conventional-changelog-writer): writerOpts supports timeZone

---

packages/conventional-changelog-writer/src/context.ts
packages/conventional-changelog-writer/src/options.ts
packages/conventional-changelog-writer/src/template.spec.ts
packages/conventional-changelog-writer/src/types/options.ts
packages/conventional-changelog-writer/src/utils.ts
packages/conventional-changelog-writer/src/writers.spec.ts
packages/conventional-changelog-writer/src/writers.ts

BREAKING CHANGES: `timeZone` option was removed, please use `formatDate` option to change timezone of a date.
closes #1186

feat(conventional-changelog-writer)!: `formatDate` option

---

.github/workflows/ci.yaml

When a contributor wants to create a PR for this repo, the normal thing for her to do first is fork the repo and create a branch with a different name than master. Then, if she pushes her commits, she should be able to see the CI status of her fixes before opening a PR.

ci: no need to just run in master branch

---

README.md

`standard-version` has been deprecated and it recommends it's fork commit-and-tag-version.

docs: change recommended high-level library

---

packages/conventional-commits-parser/src/CommitParser.spec.ts
packages/conventional-commits-parser/src/CommitParser.ts

At the moment `CommitParser.parse` does not set `type`, `scope`, or `subject` when the commit includes an exclamation mark to indicate a breaking change. E.g. `feat(hello/world)!: message`.
This pull request addresses that so that they are available to use post parsing for all commits.

Parse header if subject includes ! to indicate breaking change

---

packages/conventional-changelog-angular/src/parser.js
packages/conventional-changelog-angular/test/index.spec.js

As per their spec, there is no period required at the end of the commit SHA:
https://github.com/angular/angular/blob/main/CONTRIBUTING.md#revert-commits
Also, as a fix, I set a minimum requirement of 7 characters for the SHA ([Git default](https://stackoverflow.com/a/18134919)) as currently you can pass in nothing and it would still work.

fix(angular): revert pattern to not require a period

---

packages/conventional-changelog-conventionalcommits/src/templates/template.hbs

fix(conventional-changelog-conventionalcommits): avoid double empty lines

---

packages/conventional-changelog-conventionalcommits/README.md

I was getting onboarded to conventional-changelog and had a confusing time trying to get customization working
Turns out that the `name` for `preset` needs to match the `npm` package name? `conventional-changelog-conventionalcommits` instead of `conventionalchangelog`
Also updating some outdated 404 links

Update README.md - fix links, example json
